[package]
name = "seanvim"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
nvim-oxi = { version = "0.6.0", features = ["neovim-0-11"] }
futures = "0.3.31"
libuv = "2.12.0"
libuv-sys2 = "1.51.0"
